import "./globals.css";
import Navbar from "../components/general/Navbar";
import Footer from "../components/general/Footer";
import { Inter } from "@next/font/google";
import ScrollProgress from "@/components/general/ScrollProgress";
import TabBar from "@/components/about/TabBar";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Stevan's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <ScrollProgress />
        <header className="flex justify-center my-6 top-6 sticky z-[10]">
          <Navbar />
        </header>
        <TabBar />

        {children}
        <Footer />
      </body>
    </html>
  );
}
