import "./globals.css";
import Navbar  from "../components/Navbar";

// npm i @next/font
import { Inter } from '@next/font/google';

const inter = Inter({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900'],
  variable: "--font-inter"
});



export const metadata = {
  title: "Stevan's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        

        <header className="justify-center">
          <Navbar/>
        </header>
        
        {children}
      </body>
    </html>
  );
}
