import "./globals.css";
import Navbar from "../components/general/Navbar";
import Footer from "../components/general/Footer"; 
// npm i @next/font
import { Inter } from '@next/font/google';

const inter = Inter({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900'],
  variable: "--font-inter"
});



export const metadata = {
  title: "Stevan's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} overflow-x-hidden`}>
        
        <header className="flex justify-center my-6 top-6 sticky z-[100]">
          <Navbar/>
        </header>
    
        {children}

        {/* <Footer/> */}

      </body>
    </html>
  );
}
